### PR TITLE
Support p2sh addresses and more

### PR DESCRIPTION
**Pull request by weilu**
I'm just throwing this one out see what @jprichardson thinks :P If you feel emotionally attached to the dependencies I dropped, feel free to close this. No hard feelings.
- Drop a bunch dependencies and use bitcoinjs-lib instead. I'm pointing to master because I want to use `ECPair`.
- Serialized wallet is in plaintext, WIF instead of a bip39 mnemonic, for simplicity.

### CODE REVIEW

**Comment by jprichardson** [comment]
I'm fine with almost all of this :) I don't however like the lack of the JSON file wallet, bip39, and URL endpoint changes as I wanted to support other coins. Hmm. I may accept this, publish and tag `1.0` and when I get around to actually supporting other coins, do that in `2.0`....

**Comment by weilu** [comment]
Feel free to revert the wallet and URL part if you decide to merge. I wasn't sure what your plan was going forward so I simplified it to the bare minimum :)

**Comment by jprichardson** [comment]
Cool. Ok, before I merge... what was the problem that you had with `p2sh` addresses? I rarely use them so I'm probably missing something very obvious.

**Comment by weilu** [comment]
`spend` only handles pubkeyhash: https://github.com/jprichardson/spend/blob/master/lib/spend.js#L14 while `bitcoinjs-lib` handles both: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/address.js#L54-L55

**Pull request merged**
